[package]
name = "Filtering-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = { version = "0.35.0", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
log = "0.4"
env_logger = "0.11.8"

[profile.release]
opt-level = 3
